spring:
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:kafka-test:9092}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-test}:8761/eureka/

logging:
  level:
    root: INFO
